### ISSUE TITLE
OrchestrationTrigger functions failed to start after upgrading to Sdk 1.16.0

### ISSUE THREAD

**Issue by larry-lau** [Azure/azure-functions-dotnet-worker#2040]
After upgrade to Microsoft.Azure.Functions.Worker.Sdk 1.16.0, OrchestrationTrigger functions failed to start with the follow error.
The function works with version 1.15.1.  For now, we reverted back to 1.15.1.

The following are the error logs: 
`
Error converting 1 input parameters for Function 'xxxxxx': Cannot convert input parameter 'context' to type 'Microsoft.DurableTask.TaskOrchestrationContext' from type 'System.String'. Error:System.Text.Json.JsonException: 'C' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: 'C' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, JsonTypeInfo jsonTypeInfo, ReadStack& state)
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.ReadFromStreamAsync[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at Microsoft.Azure.Functions.Worker.Converters.JsonPocoConverter.GetConversionResultFromDeserialization(Byte[] bytes, Type type) in D:\a\_work\1\s\src\DotNetWorker.Core\Converters\JsonPocoConverter.cs:line 66
`

`
   at Microsoft.Azure.Functions.Worker.Context.Features.DefaultFunctionInputBindingFeature.BindFunctionInputAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultFunctionInputBindingFeature.cs:line 105
   at CEA.Funcs.DirectFunctionExecutor.ExecuteAsync(FunctionContext context) in C:\xxxx-agent01\_work\5\s\src\Engine\Funcs\Microsoft.Azure.Functions.Worker.Sdk.Generators\Microsoft.Azure.Functions.Worker.Sdk.Generators.FunctionExecutorGenerator\GeneratedFunctionExecutor.g.cs:line 34
   at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
   at Microsoft.Azure.Functions.Worker.Extensions.DurableTask.DurableTaskFunctionsMiddleware.Invoke(FunctionContext functionContext, FunctionExecutionDelegate next) in /_/src/Worker.Extensions.DurableTask/DurableTaskFunctionsMiddleware.cs:line 22
   at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 77
   at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 88
`

**Comment by jviau** [comment]
https://github.com/microsoft/durabletask-dotnet/issues/232

You have a few options to address this:

1. Update to Durable extension `1.1.0-preview.2`
2. **Or** disable function metadata source gen: `<FunctionsEnableWorkerIndexing>false</FunctionsEnableWorkerIndexing>`

@satvu @kshyju - I thought the casing issue was addressed before release 1.16.0?

**Comment by kshyju** [comment]
We have released [Microsoft.Azure.Functions.Worker.Sdk 1.16.1](https://github.com/Azure/azure-functions-dotnet-worker/releases/tag/sdk-1.16.1) which includes a fix for this issue. Please upgrade to that version and let us know if you are still experiencing issues. Thank you! 

[https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Sdk/1.16.1]https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Sdk/1.16.1)

**Comment by DL444** [comment]
I just updated the SDK to 1.16.1 and could verify that least my issue in https://github.com/microsoft/durabletask-dotnet/issues/232 was resolved.

**Comment by larry-lau** [comment]
I was able to confirm that version 1.16.1 fixed my issue as well. Really appreciate the fast turnaround!

**Comment by dhananjaytyagi24** [comment]
I am on the latest sdk, worker packages but I am still facing this issue.-

Function 'xyz', Invocation id 'abc': An exception was thrown by the invocation.
Result: Function 'xyz', Invocation id 'abc: An exception was thrown by the invocation.
Exception: Microsoft.Azure.Functions.Worker.FunctionInputConverterException: Error converting 1 input parameters for Function 'xyz': Cannot convert input parameter 'input' to type 'System.Collections.Generic.IReadOnlyList`1[my_object_type]' from type 'System.String'. Error:System.Text.Json.JsonException: The JSON value could not be converted to Enums.type. Path: $[0].entityType | LineNumber: 0 | BytePositionInLine: 340.
