### ISSUE TITLE
Isolated functions with .NET 8 - The gRPC channel uri could not be parsed

### ISSUE THREAD

**Issue by briandunnington** [Azure/azure-functions-dotnet-worker#2099]
Steps to reproduce:
- using Visual Studio 17.8.1
- create a new Function app targeting .NET 8 Isolated (i chose an HttpTrigger, but it doesnt really matter)
- delete the contents of the `obj` folder, wait a few seconds, and delete the contents again (VS appears to recreate the nested `Debug` folder so you have to do it twice)
- F5 debug the app
- Notice the exception

this might seem like "dont do that" behavior, but this mimics our CI build server that builds in a completely clean environment without VS. when we build and try to run there, we encounter the same error.

investigation shows that `configuration["HOST"]` and `configuration["Functions:Worker:HostEndpoint"]` are both null (but `configuration["PORT"]` is properly set), which causes `GetFunctionsHostGrpcUri()` in `GrpcServiceCollectionExtensions` to fail.

note that subsequent runs (when the files in the `obj` folder exist) all work like normal and the `configuration` values are present.

@fabiocav @kshyju 

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/1545776/e0085657-723c-40ee-b32f-5fd7f59cf9c7)

**Comment by briandunnington** [comment]
> How are you running it in your CI environment? Are you doing `dotnet run` or `func host start` ?

`func start -p XXXX`

**Comment by kshyju** [comment]
You are running `func host start` after publishing your function app. correct? The `dotnet publish` should create the right artifacts for you in the publish output directory and running `func host start` there should work. Can you confirm you are doing this sequence?

```bash
>dotnet publish -c release -o .\out
>cd .\out
>func host start
```

**Comment by tbasallo** [comment]
We're having this same issue running from VS2023. It works for some, not for others. This is a brand new project with a single HTTP function.

**Comment by kshyju** [comment]
@tbasallo Could you please share a minimal repro of this issue so that we can take a closer look? A link to a GitHub repo would be great.

**Comment by mikkovor** [comment]
Getting the same error on a fresh function when deployed from visual studio (17.8.3) to azure

**Comment by kshyju** [comment]
@mikkovor See https://github.com/Azure/azure-functions-dotnet-worker/issues/2121#issuecomment-1847281008

**Comment by victormarante** [comment]
I am having the same issue as others have mentioned, namely creating a brand new Functions via Core tools, creating a simple HttpTrigger (though using the ...Http.AspNetCore extension), but other then that I have the same set up.

See attached files for output from console (P.S. I tried both `func host start` and what you mentioned in ([this](https://github.com/Azure/azure-functions-dotnet-worker/issues/2099#issuecomment-1835268248)) comment

[Repo](https://github.com/victormarante/azure-func-http-trigger-repo)

[output.log](https://github.com/Azure/azure-functions-dotnet-worker/files/13637223/output.log)

**Comment by NicolaiSattler** [comment]
@nibblesnbits, for the `WebApplicationFactory` this problem is solved with #2121 (as @kshyju mentioned).

**Comment by Wangor** [comment]
the issue is still valid, also with 

Core Tools Version:       4.0.5455 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.27.5.21554

**Comment by nibblesnbits** [comment]
> the issue is still valid, also with
> 
> Core Tools Version: 4.0.5455 Commit hash: N/A (64-bit) Function Runtime Version: 4.27.5.21554
> 
> Used the original template from VS 2023, all latest Version.


Yeah, this is definitely not "completed."

**Comment by Wangor** [comment]
Please bring a working solution fast, it is a pitty when you crashed it and there is no solution. (Or name at least the correct downgrades)

**Comment by kshyju** [comment]
#2121 is tracking the fix for the issue.

**Comment by dheerajawale-svg** [comment]
is it fixed?

**Comment by cwistedt** [comment]
> is it fixed?

I am wondering the same thing. I am not able to create a simple azure function from scratch using azure functions core tools and run it locally without any changes. I am really confused. This is my setup:

OS: Ubuntu 22.04.4 LTS

Azure Functions Core Tools
Core Tools Version:       4.0.5530 Commit hash: N/A +c8883e7f3c06e2b424fbac033806c19d8d91418c (64-bit)
Function Runtime Version: 4.28.5.21962

dotnet --list-sdks
6.0.419 [/usr/share/dotnet/sdk]
8.0.200 [/usr/share/dotnet/sdk]

dotnet --list-runtimes
Microsoft.AspNetCore.App 6.0.27 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 8.0.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.27 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 8.0.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Create Azure Function:
![Screenshot from 2024-03-03 12-52-34](https://github.com/Azure/azure-functions-dotnet-worker/assets/20359067/08d17d0b-7cf0-48cd-8e41-5d3395be9888)

Run Azure Function:
![Screenshot from 2024-03-03 12-55-24](https://github.com/Azure/azure-functions-dotnet-worker/assets/20359067/4f9a215e-54d2-47db-be1f-688ab4ff4982)

ps. func host start generates same error

**Comment by cwistedt** [comment]
Nevermind. Found the issue. I had the proxy-service cntlm installed and it did not support http/2. After uninstalling it everything worked.

**Comment by BalindraEptura** [comment]
I'm getting the same error
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/125865904/ccccb84c-8468-43ba-970e-2e833ee758cf)

**Comment by CNBoland** [comment]
Bumped into this today on an existing project. Turned out to be a compatibility issue with Microsoft.Azure.Functions.Worker.Sdk v1.17.2 and Azure Functions Core Tools v4.0.5907. Updating that package to v1.17.4 (latest) solved it. \#sharpenTheSaw

**Comment by theplankmeister** [comment]
I am experiencing a very similar issue when attempting to run integration tests. [I created a repo](https://github.com/theplankmeister/dotnet8IntegrationTesting) that demonstrates the issue, with the integration tests working as expected in .Net6 in-proc, while failing in .Net8 isolated.

The exact error I see is

```
System.InvalidOperationException : The gRPC channel URI 'http://:50084' could not be parsed.
```

...where the port number changes for each execution. This error occurs when attempting to [start the host](https://github.com/theplankmeister/dotnet8IntegrationTesting/blob/99b35381a0ab7bfebd68ae76b16510fe34364f45/src/DotNet8.Tests.Integration/TestInitialiser.cs#L38)

In this simplified example, running the host is not necessary, but my use case is for running integration tests on durable functions, which requires that the host be running.

Has anybody else seen this issue and managed to figure out a solution?

**Comment by Vidushi1107** [comment]
I am also facing the same issue whole creating Test Host inside my Unit Test. Any solutions ?

**Comment by JerryNixon** [comment]
Similar if not same.

> An unhandled exception of type 'System.InvalidOperationException' occurred in System.Private.CoreLib.dll: 'The gRPC channel URI 'http://:' could not be parsed.'

I am launching from VSCode.

### launch.json

```json
        {
            "name": "Launch Azure Function",
            "type": "coreclr",
            "request": "launch",
            "program": "${workspaceFolder}/src/Api/bin/Debug/net8.0/Api.dll",
            "cwd": "${workspaceFolder}/src/Api",
            "preLaunchTask": "run-azure-function",
            "stopAtEntry": false,
            "args": ["--urls", "http://localhost:1000"],
            "serverReadyAction": {
                "action": "openExternally",
                "pattern": "\\bNow listening on:\\s+(https?://\\S+)",
                "uriFormat": "http://localhost:1000/api/Now"
            },
        }
```

### tasks.json

```json
        {
            "label": "run-azure-function",
            "command": "func",
            "type": "shell",
            "args": [
                "start",
                "--script-root",
                "${workspaceFolder}/src/Api"
            ],
            "problemMatcher": {
                "pattern": [
                    {
                        "regexp": ".*", // Matches any output
                        "file": 1,
                        "location": 2,
                        "message": 3
                    }
                ],
                "background": {
                    "activeOnStart": true,
                    "beginsPattern": ".*Azure Functions Core Tools.*",
                    "endsPattern": ".*Worker process started and initialized.*"
                }
            },
            "isBackground": true
        },
```

**Comment by rwb196884** [comment]
Just started getting this after updating VisualStudio to 17.12.1.

I used to click 'play' in VisualStudio and it worked. Now it says `System.InvalidOperationException: 'The gRPC channel URI 'http://:' could not be parsed.'`. What do I need to do?

**Comment by bingqiangxiang** [comment]
Also getting this after updating VisualStudio to 17.12.3.

**Comment by kshyju** [comment]
When you encounter this error, please open Task Manager and check the **Command Line** value for the .NET Host entry associated with your application. The process that triggered this error should still be running. That information should help us investigate this further.

**Comment by bingqiangxiang** [comment]
re-install the visual studio works for me

**Comment by tobiashoefer-kro** [comment]
I had the same issue when i started the functions runtime from visual studio (F5). Running `func host start` in the terminal worked without any issues. 

Updating `Microsoft.Azure.Functions.Worker.Sdk` from `1.17.2` to `2.0.0` fixed the issue for me. Now it work from Visual Studio again.

**Comment by rwb196884** [comment]
@kshyju there is no `dotnet.exe` process listed in TaskManager.

@tobiashoefer-kro using `Microsoft.Azure.Functions.Worker.Sdk` version `2.0.0`.

Issue closed? So: AzureFunctions are unusable. Alternatives?
