### ISSUE TITLE
HttpRequestData.CreateResponse(StatusCode) throwing IFeatureCollection disposed from HttpTrigger functions

### ISSUE THREAD

**Issue by elliot-j** [Azure/azure-functions-dotnet-worker#2462]
### Description

 I've created a extension method for to simplify returning JSON and some common error codes.

Extension methods
```
public static async Task<HttpResponseData> CreateJsonResponseAsync(this HttpRequestData request, HttpStatusCode code, object response)
{
    HttpResponseData rep = request.CreateResponse(code);
    rep.Headers.Add("Content-Type", "application/json");
    await rep.WriteStringAsync(JsonConvert.SerializeObject(response));
    return rep;
}
public static async Task<HttpResponseData> CreateInternalServerResponseAsync(this HttpRequestData req, string message)
{
    var rep = req.CreateResponse(HttpStatusCode.InternalServerError);
    rep.Headers.Add("Content-Type", "text/plain");
    await rep.WriteStringAsync(message);
    return rep;
}
```
For what ever reason, two straightforward HttpTrigger endpoints in an isolated function app are randomly (but semi-regulary) giving the following exception message  when deployed to Azure, causing some requests that would otherwise be successful to fail
```
 Application Error - IFeatureCollection has been disposed.
Object name: 'Collection'. -    at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.ThrowContextDisposed()
   at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.ContextDisposed()
   at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.Fetch[TFeature](TFeature& cached, Func`2 factory)
   at Microsoft.AspNetCore.Http.DefaultHttpResponse.set_StatusCode(Int32 value)
   at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.AspNetCoreHttpResponseData.set_StatusCode(HttpStatusCode value) in D:\a\_work\1\s\extensions\Worker.Extensions.Http.AspNetCore\src\HttpDataModel\AspNetCoreHttpResponseData.cs:line 40
   at Microsoft.Azure.Functions.Worker.Http.HttpRequestDataExtensions.CreateResponse(HttpRequestData request, HttpStatusCode statusCode) in D:\a\_work\1\s\src\DotNetWorker.Core\Http\HttpRequestDataExtensions.cs:line 134
   at Insight.Functions.Core.Extensions.FunctionAppExtensions.CreateJsonResponseAsync(HttpRequestData request, HttpStatusCode code, Object response)

```
Sample HttpTrigger function
```
[Function(MethodNames.SDLElements_LoadChoiceFields)]
public  async Task<HttpResponseData> LoadElementsChoiceFieldsAsync(
   [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = MethodRoutes.SDLElements_LoadChoiceFields)] HttpRequestData req)
{
    try
    {
        var request = await RequestParsingHelper.ReterieveValueFromRequestAsync<WorkItemPostRequest>(req);

        var result = await _elementService.LoadChoiceFieldsAsync(request,ItemSourceEnum.SDL);

        return await req.CreateJsonResponseAsync(HttpStatusCode.OK, result);
    }
    catch (Exception ex)
    {
        _errorLoggingRepository.LogError($"{nameof(SDLElementsController)}.{MethodNames.SDLElements_LoadChoiceFields}:  {APIResponse.ERROR_APPLICATION} - {ex.Message} - {ex.StackTrace}");
        return await req.CreateInternalServerResponseAsync(ex.Message);
    }
}
```

I saw a similar error in  #2205  which suggested removing the AspNetCore integration. I tried to remove the integration in the manner it suggested but when the app builds it ends up giving `The registration for method 'ConfigureFunctionsWebApplication' is expected for ASP.NET Core Integration.`	I'm not sure if this is because I missed some setting or a transient dependency is forcing me to use it.

### Steps to reproduce

Build Targets
```
<PropertyGroup>
	<TargetFramework>net6.0</TargetFramework>
	<AzureFunctionsVersion>v4</AzureFunctionsVersion>
        <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
        <OutputType>Exe</OutputType>
</PropertyGroup>
```

Installed Nuget Package

```
<FrameworkReference Include="Microsoft.AspNetCore.App" />
<PackageReference Include="AzureFunctions.Autofac" Version="4.0.3" />
<PackageReference Include="Autofac.Extensions.DependencyInjection" Version="8.0.0" />
<PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.MessagePack" Version="8.0.4" />
<PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.22.0" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.SignalRService" Version="1.13.1" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.17.2" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="1.2.1" />
<PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.22.0" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="1.2.0" />
<PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.DurableTask" Version="1.1.1" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.1.0" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.3.0" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.OpenApi" Version="1.5.1" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="5.16.0" />
```

**Comment by kshyju** [comment]
@elliot-j I attempted to reproduce this issue by copying and using the extension method in a minimal HTTP app (using `ConfigureFunctionsWebApplication` in main) and running a load test with 100,000 requests, observing a 0% failure rate. Could you provide a minimal reproduction of the issue, preferably with a link to a GitHub repository?

**Comment by elliot-j** [comment]
@kshyju  I'll need a few days to get back to you on a repro sample

**Comment by elliot-j** [comment]
@kshyju I have not been able to get this isolated in repro sample. However, we did find that swapping to `IActionResult` return types removes this error for us. Since we have a work around I'm fine with closing out this issue.

**Comment by slaneyrw** [comment]
This is causing all endpoints from Microsoft.Azure.Functions.Worker.Extensions.OpenApi to now throw exceptions as they return HttpResponseData.

This was working previous in .NET 8 / Isolated.  We use a floating NuGet version so I can't isolate exactly when this broke

**Comment by satvu** [comment]
Closing as original issue is resolved - the issue @slaneyrw is referencing is a bug in `1.3.0` of the extension and is fixed in `1.3.1`.

**Comment by ajinkya-ugane-ecc** [comment]
Hi,

I'm still getting this issue with my Azure function. All of a sudden it started appearing while creating response.

I have gone through lot of articles. Tried changing the response from HttpResponseData to new OkObjectResult. Upgraded all the Microsoft.Azure.Functions.Worker related packages to latest versions.

I have noticed one thing that is when function takes longer time to respond say 3 minutes or so then I get this error and not when function takes few seconds.

Also this error from the post only occurs for function app in Azure portal and locally I get some different error as below:-

_System.Private.CoreLib: Exception while executing function: Functions.RiskOperations. Microsoft.Azure.WebJobs.Script.Grpc: Failed to proxy request with ForwarderError: RequestTimedOut. System.Net.Http: The operation was canceled. System.Net.Sockets: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request.. The I/O operation has been aborted because of either a thread exit or an application request._

Below are some of the code details from my application:-

**Program.cs file**

var host = new HostBuilder()
    .ConfigureFunctionsWebApplication()
    .ConfigureServices(services =>
    {
        services.AddApplicationInsightsTelemetryWorkerService();
        services.ConfigureFunctionsApplicationInsights();
        services.AddHttpClient();
        services.AddOptions<FunctionConfigurations>()
        .Configure<IConfiguration>((settings, configuration) =>
        {
            configuration.Bind(settings);
        });
        services.AddScoped<IServiceCollection>(provider => services);

        services.AddScoped<IHttpService, HttpService>();
        services.AddScoped<ICRMService, CRMService>();
        services.AddScoped<IIntegrationService, IntegrationService>();
        services.AddScoped<IIPlusAPCQuoteOperationsProcessor, IPlusAPCQuoteOperationsProcessor>();
        services.AddScoped<IIPlusAPCRiskOperationsProcessor, IPlusAPCRiskOperationsProcessor>();
        services.AddScoped<IIPlusAPCRiskLocationOperationsProcessor, IPlusAPCRiskLocationOperationsProcessor>();
        services.AddScoped<IIplusAPCInterestedPartyOperationsProcessor, IplusAPCInterestedPartyOperationsProcessor>();
        services.AddScoped<IIplusAPCJointInsuredOperationsProcessor, IplusAPCJointInsuredOperationsProcessor>();
        services.AddScoped<IIplusAPCQuoteAdditionalInsOperationsProcessor, IplusAPCQuoteAdditionalInsOperationsProcessor>();

        services.AddTransient<CRMHelper>();
    })
    .ConfigureLogging(logging =>
    {
        logging.Services.Configure<LoggerFilterOptions>(options =>
        {
            LoggerFilterRule defaultRule = options.Rules.FirstOrDefault(rule => rule.ProviderName
                   == "Microsoft.Extensions.Logging.ApplicationInsights.ApplicationInsightsLoggerProvider");

               if (defaultRule is not null)
               {
                   options.Rules.Remove(defaultRule);
               }
        });
     })
    .Build();

host.Run();


**Function .csproj file** 

<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.22.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.2.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="1.3.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.17.2" />
    <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.22.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="1.2.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ecclesiastical.Crm.BusinessLogic\Ecclesiastical.Crm.BusinessLogic.csproj" />
    <ProjectReference Include="..\Ecclesiastical.Crm.Common\Ecclesiastical.Crm.Common.csproj" />
    <ProjectReference Include="..\Ecclesiastical.Crm.Services\Ecclesiastical.Crm.Services.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Using Include="System.Threading.ExecutionContext" Alias="ExecutionContext" />
  </ItemGroup>
</Project>

**Function code:-** 

namespace IPlusAPCRiskOperations
{
    public class RiskOperations
    {
        private readonly ILogger<RiskOperations> _logger;
        private IIPlusAPCRiskOperationsProcessor _processor;

        public RiskOperations(ILoggerFactory loggerFactory, IIPlusAPCRiskOperationsProcessor processor)
        {
            _logger = loggerFactory.CreateLogger<RiskOperations>();
            _processor = processor;
        }

        [Function("RiskOperations")]
        public async Task<HttpResponseData> RunAsync([HttpTrigger(AuthorizationLevel.Function, "get", "post")] HttpRequestData req)
        {
            try
            {
                _logger.LogInformation("Azure function execution started.Invocation Id:- " + req.FunctionContext.InvocationId);
                string? jsonContext = await req.ReadAsStringAsync();                
                _logger.LogInformation(jsonContext);
                string iplusAPCResponse = _processor.ProcessRequest(jsonContext);
                var response = req.CreateResponse(HttpStatusCode.OK);
                await response.WriteStringAsync(iplusAPCResponse);
                _logger.LogInformation("Azure function execution finished. Invocation Id: -" + req.FunctionContext.InvocationId);
                return response;
            }
            catch (Exception ex)
            {
                _logger.LogError("Error:- " + ex.ToString());
                var response = req.CreateResponse(HttpStatusCode.InternalServerError);

                return response;
            }
        }
    }
}
