### ISSUE TITLE
Upgrading Microsoft.Azure.Functions.Worker.Extensions.EventGrid to 3.4.3

### ISSUE THREAD

**Issue by badmandragon** [Azure/azure-functions-dotnet-worker#2909]
### Description

Upon upgrading `Microsoft.Azure.Functions.Worker.Extensions.EventGrid` from `3.4.2` to `3.4.3`, when deployed to Azure Function app, the following error was observed at startup 
`Microsoft.Azure.WebJobs.Extensions.EventGrid: Could not load file or assembly 'System.Memory.Data, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.`

### Steps to reproduce

Upgrade the package very for `Microsoft.Azure.Functions.Worker.Extensions.EventGrid` from `3.4.2` to `3.4.3`

**Comment by aherrick** [comment]
i'm seeing this as well. downgraded

**Comment by markti** [comment]
Also seeing the same issue with 3.4.3

**Comment by oysterbay73** [comment]
I wish I'd seen this before! Same issue. For info I noticed that it's looking for System.Memory.Data.dll in the .azurefunctions sub-folder  so if you manually copy it there from the folder above then 3.4.3 will work (but I would recommend sticking with 3.4.2)

**Comment by amayfoxen** [comment]
We saw the same issue - strangely I don't see 3.4.3 at nuget.org: https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.EventGrid

**Comment by Trimatix** [comment]
Just run into this as well via a transitive dependency. Adding an exception in dependabot now, but this package version is 6 months old!

Team, please could this issue be triaged?

**Comment by satvu** [comment]
3.4.3 should work now as long as you are on the latest host version (4.1037), which has recently completed rollout. 

This bug was resolved by https://github.com/Azure/azure-functions-host/pull/10610 in 4.1037.

**Comment by Misiu** [comment]
This is still an issue; the new deployment was just a second ago (in the West Europe region). NET 9, Isolated worker, Linux.
downgrade to 3.4.2 helped, but I wasted 3 hours finding a solution.
Funny thing - on two other subscriptions, this worked without any issues.

**Comment by 64Soft** [comment]
Indeed, this issue still persist, with a .NET 9 isolated worker in West Europe Region. Also, it reports the same error when running the functions app locally in Visual Studio 2022. Downgrading to Microsoft.Azure.Functions.Worker.Extensions.EventGrid 3.4.2 makes it working again. I'm on the latest VS2022 update as of this writing (17.13.3).
