### ISSUE TITLE
Worker Process startup timeout (30 sec) prevents reliably debugging HostBuilder startup code

### ISSUE THREAD

**Issue by david-peden-q2** [Azure/azure-functions-dotnet-worker#434]
When launching an azure function with `func start --dotnet-isolated-debug`, visual studio pauses for a period of time to allow you to attach the debugger to the newly created process. This works fine.

What doesn't work well is that if you set a breakpoint anywhere in your `HostBuilder` code and cross the 30 second mark, the underlying process recycles because of a timeout which kills your debug session. It makes it exceedingly difficult, if not impossible, to debug anything non-trivial.

![image](https://user-images.githubusercontent.com/11466099/116921064-15830500-ac19-11eb-883b-9ddb56b6aaba.png)

**Comment by fabiocav** [comment]
Thank you for opening this!

This is an instance where our debug behavior doesn't seem to be properly applied.

@ankitkumarr this would require a host change to correctly identify the debug scenario and ensure those timeouts are not applied. We do that for a number of things and looks like this was just missed. I'll loop in additional folks as this is likely impacting other languages as well.

**Comment by fabiocav** [comment]
Discussed in triage. Some design work will be required to settle on the right behavior, we'll then open the required issues in the appropriate repos.

**Comment by jwisener** [comment]
Yes, same issue, can no longer effectively debug and develop azure function 5. It really seems like a downgrade and tooling is always a 2nd thought. So broken.

**Comment by RiaanVR** [comment]
We've just recently starting investigating.NET 5 for our stack which is exclusively built on top of functions currently .net core 3.1, wanting to take advantage of all the perf and language improvements we want to start moving toward .NET 5 ahead of the release of .NET 6 in November.

So far it is nearly impossible to get a function instance running locally so that one can debug, there are some changes that the only way to know if your function runs is either debug or going log crazy, I think you know which we all prefer. 

What's the outlook on the tooling to get functions on .NET 5 reliably debuggable?

**Comment by brettsam** [comment]
@RiannVR -- what version of Visual Studio are you using? With 16.10, hitting F5 should launch the debugger and attach correctly: https://docs.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-developer-howtos?pivots=development-environment-vs&tabs=browser#prerequisites.

There is an issue debugging startup code (https://github.com/Azure/azure-functions-dotnet-worker/issues/434), but setting a breakpoint in a function should work as expected.

Please let us know if this isn't working and we can investigate.

**Comment by jwisener** [comment]
I have an example visual studio .net project, with a basic set of timer functions that F5 will not work properly.

**Comment by fabiocav** [comment]
I'm suspecting the issue above is related to the monitor for the timer. @jwisener do you have a storage account and/or emulator connection string setup when debugging?

**Comment by jwisener** [comment]
I just created a new azure function project in visual studio 2019 v 10.16.01, and setup 14 timer functions. So it's using the default, which is local storage emulator

![image](https://user-images.githubusercontent.com/135758/121401548-6e337500-c91e-11eb-97f9-62f97544bfc1.png)

**Comment by jwisener** [comment]
That was an example project to reproduce the issue we are having on an actual project. Our actual project, uses an azure storage account and it does the same thing. so it doesn't seem to matter if it's an actual azure "storage account" or the emulator.

**Comment by fabiocav** [comment]
Thanks. We'll take a look to see what is going on here. Can you confirm that running standalone (outside of VS/No debugger) runs as expected?

**Comment by jwisener** [comment]
Well on our actual project, running outside of "visual studio" (via command line) and attaching the debugger, the issue we have: it's not loading the appsettings files we have properly. (aka running from the command line **func host start --dotnet-isolated-debug**  and then attaching vi the debugger). So we have to have visual studio launch it as an "executable" and then attach the debugger. (it's a pain), but that is the only way I could get the appsetting files to loaded properly. But, if you set a break in the startup, you've only got 30 seconds before the debugger drops and a new process is started.

**Comment by DavidGodbold** [comment]
We are not only finding this issue when debugging locally, but also when deployed to Azure. We have this deployed to a Windows Functions App Service Plan (Consumption model) and have the app settings set as below. Please can anyone advise what might be the issue here? The errors appear to be the same as in this issue and when debugging TimerTriggers locally in VS 2019.
![image](https://user-images.githubusercontent.com/40599276/121649302-5c71df00-ca90-11eb-88fe-dfe58ce82590.png)
![image](https://user-images.githubusercontent.com/40599276/121649528-904d0480-ca90-11eb-9be2-d195ee01149e.png)

**Comment by RiaanVR** [comment]
@brettsam I tried both with VS 16.9.4 and with Rider 2021.1.3, Rider never attaches due to the func startup not returning the worker PID and VS simply starts up, and then doesn't hit any breakpoint even though they exist in the program.cs, I've also successfully attached by starting the func in cmd and then a `Debugger.Launch` which starts up VS.

**Comment by RiaanVR** [comment]
@DavidGodbold it seems you're getting function timeouts https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale#timeout the default is 5 minutes, it seems to be cancellable the current execution and then logging the end of the previous execution. 

One thing that I found 'odd' was that with dotnet-isolated you don't get cancellation token support so how does it cancel really then if you are doing an outbound call?

**Comment by DavidGodbold** [comment]
Thanks @RiaanVR, but these TimerTrigger functions work OK if I run the code locally using the Core Tools invoked from Powershell, but suffer the timeout issue when using the VS native debugging. However the real blocker is the fact that our functions suffer the same timeout issue even when deployed to Azure.

**Comment by DavidGodbold** [comment]
@brettsam I'm disappointed to have issue 488 merged into this issue as we are suffering the same timertrigger function timeout issue even when the functions are deployed to an Azure functions instance. These functions run fine from my local machine when running func.exe using the Core Tools v3 though.

**Comment by fabiocav** [comment]
@DavidGodbold I want to make sure we're not missing something about your scenario. #488 is about a VS debugging issue and you're talking about running into this with a deployed App. Are you running into problems with a remote debugging scenario? Or purely running into timeouts outside of debugging scenarios?

**Comment by louisoftokyo** [comment]
I'm also having this issue now, locally. I'd been debugging TimerTriggers locally a couple of months ago so I'm not sure what changed. My functions work in Azure.

**Comment by DavidGodbold** [comment]
> @DavidGodbold I want to make sure we're not missing something about your scenario. #488 is about a VS debugging issue and you're talking about running into this with a deployed App. Are you running into problems with a remote debugging scenario? Or purely running into timeouts outside of debugging scenarios?

@fabiocav I am having issues with running into timeouts outside of debugging scenarios (as well as experiencing the issues raised within this issue). Please see my comment [here](https://github.com/Azure/azure-functions-dotnet-worker/issues/434#issuecomment-859362267)

**Comment by ThreeSevenths** [comment]
Just installed 16.10.2 released today and a new Functions project out of the box is still broken out of the box. What do you need from us to help you find and fix this issue?

![image](https://user-images.githubusercontent.com/1298072/122139215-7b68cc00-ce16-11eb-962e-d5ae3330846f.png)

**Comment by DavidGodbold** [comment]
Just a quick update. Creating a function app using the Azure CLI and deploying using the Azure Pipelines seemed to work and the functions work as expected. It probably needs to be made clear that creating a function app using the Portal and changing the app settings to run dotnet-isolated will not work. This was using a consumption plan. 

`az functionapp create --name $functionAppName 
  --storage-account $storageName 
  --consumption-plan-location $region 
  --resource-group $resourceGroup 
  --subscription $subscription 
  --runtime dotnet-isolated 
  --runtime-version 5.0 
  --functions-version 3 `

**Comment by fabiocav** [comment]
The fix has now been merged into the host. Just pending deployment at this point.

Keeping this open until the Core Tools version with the changes is available.

**Comment by maartenba** [comment]
What will be the steps to configure timeout? Is it per-app or global for the (isolated) worker?

**Comment by brettsam** [comment]
You shouldn't have to touch anything here. When debugging, the tooling will extend the worker timeout automatically.

**Comment by ThreeSevenths** [comment]
> The fix has now been merged into the host. Just pending deployment at this point.
> 
> Keeping this open until the Core Tools version with the changes is available.

Do you know when the fix will be released and be integrated into VS?

**Comment by vijayrkn** [comment]
@brettsam - Could this also be related to the same issue? https://developercommunity.visualstudio.com/t/Azure-functions-debug-fails-to-start-on-/1474373

There is a sample repo available in the devcom issue.

**Comment by fabiocav** [comment]
@vijayrkn it's a slightly different issue, but this fix will help with it. Though, the repro shared there seems to require additional (unexpected) steps, so I'd like to validate that. There's some additional work we're considering in the WebJobs SDK/Host layer to address the timer initialization issue

@ThreeSevenths the Core Tools update will happen once global deployment of the changes completes, which we estimate will happen at the end of next week (by July 30th), due to deployment restrictions. We can, however, share details on how you can use the version of Core Tools that targets that version before then, if needed.

**Comment by ImranShafqat-123** [comment]
I am still getting the timeout error but only for Timer functions. When we comment out the timer function and leave the others running, debug tools work fine. Do we have a fix to this problem yet? 
![image](https://user-images.githubusercontent.com/81795094/130023325-f3b646eb-d87b-44eb-bb28-bd0d1e3c1148.png)

**Comment by drewbj21** [comment]
I am having the same issue as @ImranShafqat-123... I confirmed that I am running the latest versions of VS (16.11.1), Microsoft.Azure.Functions.Worker (1.5.1), and Microsoft.Azure.Functions.Worker.Extensions.Timer (4.1.0). The confusing part is that I was able to get my app with a queue trigger function and a timer trigger function to work end of last week but am not able to do so this week. Any help on this would be greatly appreciated!

**Comment by mikewop** [comment]
Running into the same issue here. Azure Function app in Visual studio 16.11.2 with .Net5 gets the "Starting worker process failed" when trying to debug the next day or after the scheduled event is past due.
Workaround as mentioned (@cgronseth) is to change the cron schedule slightly.
Is there any ETA on a fix?

**Comment by FlavioSpedaletti** [comment]
The workaround for me was to clear the blob service in the AzureStorageEmulator.exe, but still waiting for a definitely solution.

![clear blob](https://user-images.githubusercontent.com/6178035/134774980-d94dfcc5-db7a-4cb6-90d3-b70d897e5de7.PNG)

**Comment by rmourato** [comment]
I'm suffering the same problem in VS2019 v16.11.3 running my .NET 5 isolated function, whether I run against the Azure Storage Emulator or Azurite.

Managed to work around it using VSCode with the latest version of the Azure Functions Core Tools (3.0.3734). This lets me debug the function just fine and, so far, has never hung.
Not the ideal experience but gets things going until this is resolved.

**Comment by timritzer** [comment]
Can confirm that a past due timer interval also causes debugging to hang when trying to use the direct from VS launch option. Very annoying, causes the development experience for our team to be a mess.

**Comment by GearTheWorld** [comment]
Visual Studio 2022 Preview 4.1 works just fine.  VS 2019 Version 16.11.4 isn't working.  Same problem as everybody!
Azure Function, Timer Trigger, .NET 5.0 Just the template, nothing else

**Comment by GearTheWorld** [comment]
I tried some things here

Loaded the project started in 2022 into 2019 no luck
Loaded the project started in 2019 into 2022 no luck
Started new project using .NET Framework rather than .NET 5 in 2019 no luck
Modified the crontab no luck
Added RunOnStartup no luck

**Comment by mikewop** [comment]
> The workaround for me was to clear the blob service in the AzureStorageEmulator.exe, but still waiting for a definitely solution.
> 
> ![clear blob](https://user-images.githubusercontent.com/6178035/134774980-d94dfcc5-db7a-4cb6-90d3-b70d897e5de7.PNG)

Our current work around in VS2019 is that we added a Post-Build event that clears the blob section of the Storage Emulator as mentioned by Flavio. 
Works well for us and dramatic improvement in the debugging experience for the developers.

**Comment by satvu** [comment]
[Part 2](https://github.com/Azure/azure-functions-core-tools/pull/2666) of the fix has been merged into core tools. Pending deployment.  

[Note](https://github.com/Azure/azure-functions-host/pull/7491/files/75ebc4e6e63e2e30dc36f157b1492d694e81663b#diff-0520ea7869aafe4adf4e46cee524515169549321187cc8ecf473409fe070b53c) on how time triggers are related to the initial issues with debugging.

**Comment by fabiocav** [comment]
@david-peden-q2 / @jwisener what version of Core Tools are you running? Are you still seeing this with the latest version of the tools? 

For v3.0, this was fixed in Core Tools 3.0.3904

**Comment by ThreeSevenths** [comment]
@msftbot - Like many, I started looking at Functions in the simplest way possible - let me run something 1 minute into the future. On .NET3.1, this worked great. I then went to add EF Core, which needed to update logging to 5, and created a nightmare. The solution, it seemed, was to update to .net5, and use the new isolated process. As this thread attests, that has never worked. Like the original author, and countless others, I came to this thread to help the team debug the issue. I have been frustrated to the point of not using functions in any project by the lack of any progress to fix this problem. The salt is your bot automatically marking an issue that you have not fixed stale. It's not for lack of community involvement. 

-Trevor

**Comment by RyanMarcotte** [comment]
I am using Core Tools 3.0.3904 and the issue has been resolved for my timer-triggered function that was encountering the timeout problem.  Thanks!

**Comment by ThreeSevenths** [comment]
@fabiocav - It is fixed for me finally! I am running 3.0.3904 and I can debug again! Thank you all.

**Comment by jwisener** [comment]
@fabiocav it's still not fixed. Did anyone run the sample project I attached to this issue? Did that work? This is still an issue event in latest visual studio 2022
